[versions]
kotlin = "2.0.10"

paper = "1.19.4-R0.1-SNAPSHOT"
minestom = "9fbff439e7"

kyori = "4.17.0"

[libraries]
paper = { module = "io.papermc.paper:paper-api", version.ref = "paper" }
minestom = { module = "net.minestom:minestom-snapshots", version.ref = "minestom" }

adventureApi = { module = "net.kyori:adventure-api", version.ref = "kyori" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }